#!/bin/bash

if [ -z "$1" ]; then
	echo "Usage: $0 file"
	exit 1
fi

infile=$1
tmpfile=/tmp/xxx
name=$(basename $infile)
outfile=/tmp/${name%%.*}_E

pp_bak() {
	touch $infile
	make -j6 V=1 >$tmpfile
	rs=$(grep $name $tmpfile | grep "gcc ")
}

pp() {
	file=$(dirname $infile)/.$(echo $name | sed 's/\.[^.]*$//').o.cmd
	if [ -f "$file" ];then
		rs=$(head -n1 $file | awk -F ' := ' '{print $2}')
	else
		pp_bak
	fi
}


pp
rs="${rs%%-c -o *}"
rs=$(echo $rs -E -o $outfile $infile)
#echo $rs
eval $rs
